The course includes the following modules
Lectures:


1. Introduction to financial analytics
1.1. Introduction to financial analytics
1.2. Introduction to financial markets and basic accounting

2. Introduction to practical part
Workflow and stages: get data -> prepare data -> analyse data -> report data

Rstudio cloud and R: interface and simple operations 
Rstudio cheatsheat
https://r4ds.had.co.nz/workflow-basics.html

how to:
install packages
do simple math
tidyverse

3. Financial data:

Sources of financial data and obtaining your data: yahoo finance, uploading csv files

Examining your data: mean, range, missing data, ggplot

Data wrangling and visualization: types, basic statistics, uses, application

https://r4ds.had.co.nz/data-visualisation.html
https://r4ds.had.co.nz/transform.html


4. Examining your data

Ratio analysis

Working with financial data (any data): data sources, tidyverse, descriptives
https://r4ds.had.co.nz/exploratory-data-analysis.html
https://r4ds.had.co.nz/data-import.html


5. Descriptive analytics for financial data
Introduction to modeling
Key Ingredients of model and how to know if a model is good
Linear regression
model assessment
Analytics and visualization: cases in financial analytics 


7. introduction to financial modelling and R
https://r4ds.had.co.nz/model-building.html

8. Predictive financial modeling in R: building and assessing simple models
http://appliedpredictivemodeling.com/toc Applied Predictive Modeling by Max Kuhn

- Introduction (basics and terminology)
- A Short Tour of the Predictive Modeling Process

9. Introduction to valuation models for financial data
http://appliedpredictivemodeling.com/toc Applied Predictive Modeling by Max Kuhn

10. Advanced valuation models

11. Case studies
12. Summary


## Assessment 1:*

**Project: 25% - group work???**
1. Source data for a company for last 5 years (annual report data- statements) - dataset1
same for a competitor - dataset2

2. upload it to R

3. visualize data in R - absolute data 
company 1 vs company 2

4. calculate basic ratios
compare company 1 to company 2

5. visualise ratios for company 1 and company 2 and compare

6. build a prediction model


**Practical assignment** visualization assignment
with a given data set prepare basic transformation (one of the tidy Tuesday - makeover monday projects)

**Theory test**



